config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
    root 'portfolio#home'
    get 'home', to: 'portfolio#home', as: 'home'
    get 'projects', to: 'portfolio#projects', as: 'projects'
    get 'contact', to: 'portfolio#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioRailsD1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS BS -->
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body class="bg-dark">
    <%= render 'shared/nav' %>
    <div class="container my-3">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  <!-- JS -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>
    <%= javascript_include_tag "typed" %>
</body>
  </body>
</html>

app/views/portfolio/contact.erb
<div class="row mt-5">
	<div class="col-10 col-md-6 mx-auto">
		<div class="card p-3 bg-dark bg-gradient">
		<%= form_tag("", method: "get", id:"formulario") do %>
		  <%= tag.div class: "form-floating mb-3" do %>
		  	<%= text_field_tag(:name, "", class: "form-control", placeholder:"Nombre", required: true)  %>
		  	<%= label_tag(:name, "Nombre") %>
		  <% end %>
		  <%= tag.div class: "form-floating mb-3" do %>
		  	<%= email_field_tag(:email, "", class: "form-control", placeholder:"Email")  %>
		  	<%= label_tag(:email, "Email") %>
		  <% end %>
		  <%= tag.div class: "form-floating mb-3" do %>
		  	<%= text_area_tag(:message, "", class: "form-control", placeholder:"Mensaje", style: "height: 100px")  %>
		  	<%= label_tag(:message, "Mensaje") %>
		  <% end %>
		  <%= submit_tag("Enviar", class: "btn btn-outline-light px-4") %>
		<% end %>
		</div>
	</div>
</div>

app/views/portfolio/home.html.erb
<div class="d-flex flex-column justify-content-center min-vh-100">
  <h1 class="fs-2 text-center px-3 mb-3"><span class="typed"></span></h1>
  <p class="text-center">
    <%= link_to "Proyectos", projects_path, class: "btn btn-lg btn-outline-dark" %>
  </p>
</div>

app/views/portfolio/projects.html.erb
<div class="row" id="projects">
  <div class="col-10 col-md-6 col-lg-4 mx-auto mb-3">
    <div class="card shadow">
      <%= image_tag "iguana-page", class: "card-img-top" %>
      <div class="card-body p-0">
      <h4 class="card-title py-2 text-center text-warning bg-dark">Iguana Page</h4>
        </div>
        <div class="card-footer">
         <%= link_to "Ver código", "//github.com/mach-911/fullstack-ror/tree/iguana-page", target: "_blank", class: "my-btn" %> 
        <%= link_to "Ver demo", "//mach-911.github.io/fullstack-ror/desafios/evaluados/iguana-page/", target: "_blank", class: "my-btn" %>
        </div>
    </div>  
  </div>
  <div class="col-10 col-md-6 col-lg-4 mx-auto mb-3">
    <div class="card shadow">
      <%= image_tag "cuppons", class: "card-img-top" %>
      <div class="card-body p-0">
        <h4 class="card-title py-2 text-center text-warning bg-dark">Cuppons</h4>
      </div>
      <div class="card-footer">
        <%= link_to "Ver código", "//github.com/mach-911/fullstack-ror/tree/cuppon", target: "_blank", class: "my-btn" %> 
        <%= link_to "Ver demo", "//mach-911.github.io/fullstack-ror/desafios/evaluados/cuppon", target: "_blank", class: "my-btn" %>
      </div>
    </div>  
  </div>
 <div class="col-10 col-md-6 col-lg-4 mx-auto mb-3">
    <div class="card shadow">
      <%= image_tag "ricomida", class: "card-img-top" %>
      <div class="card-body p-0">
      <h4 class="card-title py-2 text-center text-warning bg-dark">Ricomida</h4>
        </div>
        <div class="card-footer">
         <%= link_to "Ver código", "//github.com/mach-911/fullstack-ror/tree/ricomida", target:"_blank", class: "my-btn" %>
        <%= link_to "Ver demo", "//mach-911.github.io/fullstack-ror/desafios/evaluados/ricomida/", target:"_blank", class: "my-btn" %>
        </div>
    </div>  
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="text-center fw-bold py-3 text-dark">
  Portafolio <span class="badge bg-warning text-dark">EniDev911</span>
</footer>  

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark ">
	<div class="container">
		<%= link_to "#", class: "navbar-brand" do %>
			<img src="https://raw.githubusercontent.com/EniDev911/assets/main/png/logo/logo_con_bg.png" height="50" />
		<% end %>
		<%= button_tag type: :button, 
			class: "navbar-toggler",
			data: { bs_toggle: "collapse", bs_target: "#mainNav"} do %>
				<%= tag.span class: "navbar-toggler-icon" %>
		<% end %>
		<div class="collapse navbar-collapse" id="mainNav">
			<div class="navbar-nav ms-auto">
				<%= link_to "Home", root_path, class: "nav-link" %>
				<%= link_to "Proyectos", projects_path, class: "nav-link" %>
				<%= link_to "Contacto", contact_path, class: "nav-link" %>
			</div>
		</div>
	</div>
</nav>